#!/usr/bin/env bash
# Idempotent dataset preparation script. Per CLAUDE.md, this runs inside the
# GitHub Actions workflow on Machine B before training, and writes a sentinel
# so subsequent workflow runs short-circuit when DATA_VERSION is unchanged.
#
# Metaworld doesn't ship any external dataset; D_pre is generated by
# train.py --mode=collect_pretrain on the fly. This script therefore only
# checks that mujoco can render and that the persistent cache directories
# exist — the real "preparation" happens inside train.py.

set -euo pipefail

DATA_ROOT="${DATA_ROOT:-$HOME/datasets/world-collapse}"
DATA_VERSION="${DATA_VERSION:-v1}"
DONE_FILE="$DATA_ROOT/.prepared-$DATA_VERSION"

mkdir -p "$DATA_ROOT"
mkdir -p "${HF_HOME:-$HOME/hf_cache}"
mkdir -p "${HF_DATASETS_CACHE:-$HOME/hf_cache/datasets}"
mkdir -p "${TRANSFORMERS_CACHE:-$HOME/hf_cache/transformers}"

if [ -f "$DONE_FILE" ]; then
  echo "Dataset already prepared: $DATA_ROOT, version: $DATA_VERSION"
  exit 0
fi

echo "Preparing dataset at $DATA_ROOT (version $DATA_VERSION)"

# Smoke-render a single frame to confirm mujoco is functional before we burn
# time on a real training run.
MUJOCO_GL="${MUJOCO_GL:-egl}" uv run python - <<'PY'
import metaworld
bench = metaworld.MT1("push-v3", seed=0)
env_cls = bench.train_classes["push-v3"]
env = env_cls(render_mode="rgb_array", camera_name="corner", height=64, width=64)
task = next(t for t in bench.train_tasks if t.env_name == "push-v3")
env.set_task(task)
env.reset()
frame = env.render()
assert frame is not None and frame.shape == (64, 64, 3), f"unexpected frame shape: {getattr(frame, 'shape', None)}"
print("mujoco render OK; frame shape:", frame.shape)
PY

# Pre-download the iVideoGPT tokenizer into the persistent HF cache so that
# subsequent runs hit the cache instead of pulling ~500MB every time.
# (The transformer is also pulled — small relative to the tokenizer.)
IVIDEOGPT_MODEL="${IVIDEOGPT_MODEL:-thuml/ivideogpt-oxe-64-act-free}"
echo "Pre-downloading ${IVIDEOGPT_MODEL} into HF cache at ${HF_HOME:-$HOME/hf_cache}"
uv run python - <<PY
from huggingface_hub import snapshot_download
path = snapshot_download(repo_id="${IVIDEOGPT_MODEL}")
print("snapshot_download path:", path)

import sys
sys.path.insert(0, "iVideoGPT")
import torch
from ivideogpt.vq_model import CompressiveVQModel
tok = CompressiveVQModel.from_pretrained("${IVIDEOGPT_MODEL}", subfolder="tokenizer", low_cpu_mem_usage=False)
print("tokenizer loaded; context_length =", tok.context_length, "num_vq_embeddings =", tok.num_vq_embeddings)
PY

rm -f "$DATA_ROOT"/.prepared-*
touch "$DONE_FILE"
echo "Dataset prepared."
